stages:
  preprocess:
    cmd: python3 src/data/preprocess.py --input data/raw.csv --output data/processed.csv
    deps:
      - src/data/preprocess.py
      - data/raw.csv
    outs:
      - data/processed.csv
      
  train:
    cmd: python3 src/models/train.py --data data/processed.csv --output models/model.pkl
    deps:
      - src/models/train.py
      - data/processed.csv
    outs:
      - models/model.pkl
      
  evaluate:
    cmd: python3 src/models/evaluate.py --model models/model.pkl --data data/processed.csv --output metrics/metrics.json
    deps:
      - src/models/evaluate.py
      - models/model.pkl
      - data/processed.csv
    metrics:
      - metrics/metrics.json:
          cache: false